# User Config
# ===========
# fill/change these fields to match your own.

# Identity
# --------

title:
description:

logo:  "/assets/img/logo.png"
cover: "/assets/img/cover.png"

baseurl:
url:

owner:
rights: All Right Reserved


# Social & Sharing
# ----------------

google:
  analytics:
  verification:

facebook:
  username:
  app_id:

twitter:
  username:
  large_img: sometimes

disqus:
  username:


# Content Format
# --------------

timezone: Asia/Bangkok
paginate: 10
mathjax:  true


# Engine Config
# =============
# you shouldn't change this unless you really know what you're doing.

collections:
  projects:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

permalink: date
paginate_path: "/posts/page:num"

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

plugins:
  - jekyll-sitemap
  - jekyll-paginate

empty_array: []
